"""
othello/persistence.py — Save and load game state to/from JSON files.

Provides two public functions:
  save_game(state, mode_info, path) — serialise a GameState to a JSON file
  load_game(path)                   — deserialise a JSON file back to a GameState

File format (VERSION 1)
-----------------------
{
  "version":   1,
  "size":      8,
  "current":   "BLACK",
  "mode_info": { ... },          // opaque dict from GameScreen.config_data
  "history": [
    { "row": -1, "col": -1, "color": "BLACK" },  // pass entry
    { "row": 2,  "col": 3,  "color": "WHITE" },  // normal move
    ...
  ]
}

Load strategy
-------------
Rather than storing the full board bitmap, we store only the *move sequence*
and replay it through GameState.play() when loading.  This guarantees that
the loaded state is always consistent with the game rules, and it produces
much smaller files.  The tradeoff is that load time is O(n) in the number of
moves, which is negligible for typical game lengths (≤ 60 moves on 8×8).

VERSION is stored so future format changes can be detected and an informative
error can be raised instead of a confusing KeyError or silent data corruption.
"""

import json
from pathlib import Path
from typing import Any

from othello.core.board import Color, Move
from othello.core.game import GameState

# Increment VERSION whenever the JSON schema changes in a breaking way.
VERSION = 1


def save_game(state: GameState, mode_info: dict[str, Any], path: Path | str) -> None:
    """Serialise `state` and configuration metadata to a JSON file.

    The board is not stored directly; instead we store the move history
    so the state can be reconstructed by replaying it.  Pass moves are
    stored in the history but are skipped during replay because GameState
    auto-passes as needed.

    Args:
        state:     The GameState to persist.
        mode_info: Game configuration dict from GameScreen (mode, size,
                   ai difficulty, human colour, etc.).
        path:      File path to write.  Created or overwritten.

    Raises:
        OSError: If the file cannot be written (e.g. permission error).
    """
    data = {
        "version":  VERSION,
        "size":     state.board.size,
        "current":  state.current.name,    # "BLACK" or "WHITE" — for reference only
        "mode_info": mode_info,
        # Serialise the full history so the state can be replayed on load.
        "history": [
            {
                "row":   e.move.row,
                "col":   e.move.col,
                "color": e.color_to_move.name,  # the player who made this move
            }
            for e in state.history
        ],
    }

    # indent=2 produces human-readable JSON for easy debugging of save files.
    Path(path).write_text(json.dumps(data, indent=2))


def load_game(path: Path | str) -> tuple[GameState, dict[str, Any]]:
    """Deserialise a JSON save file and replay the move history.

    Constructs a fresh GameState of the saved size and feeds every non-pass
    move through GameState.play() in order.  GameState handles auto-passing
    internally, so explicit pass entries in the history are skipped.

    A colour consistency check ensures that each history entry's recorded
    colour matches the GameState's current player at replay time.  A mismatch
    indicates a corrupted save file.

    Args:
        path: Path to the JSON save file.

    Returns:
        A (GameState, mode_info) tuple where GameState reflects the board at
        the moment the game was saved, and mode_info is the dict originally
        passed to save_game().

    Raises:
        OSError:      If the file cannot be read.
        ValueError:   If the save version is unsupported, or if a colour
                      mismatch is detected during replay.
        KeyError:     If a required JSON field is missing.
    """
    data = json.loads(Path(path).read_text())

    # Reject saves from incompatible future or past format versions.
    if data.get("version") != VERSION:
        raise ValueError(f"Unsupported save version: {data.get('version')!r}")

    size = data["size"]

    # Start from the standard opening position with an empty history.
    state = GameState(size=size)

    for entry in data.get("history", []):
        move = Move(entry["row"], entry["col"])

        # Pass moves are auto-generated by GameState during replay, so we
        # skip explicit pass entries rather than trying to play them.
        if move.is_pass:
            continue

        # Sanity check: the colour recorded in the save must match the live
        # GameState's current player at this point in the replay.
        expected_color = Color[entry["color"]]
        if state.current is not expected_color:
            raise ValueError(
                f"Replay mismatch at {move}: expected {state.current.name}, "
                f"saved as {expected_color.name}"
            )

        # Replay this move; GameState will auto-pass for the opponent if needed.
        state.play(move)

    return state, data.get("mode_info", {})
